-- Run this once in the Supabase SQL Editor for the private question workflow.
create table if not exists public.custom_prompt_submissions (
    id bigint generated by default as identity primary key,
    learner_email text not null,
    topic text not null,
    difficulty text not null,
    question text not null,
    status text not null default 'pending'
        check (status in ('pending', 'approved', 'rejected')),
    admin_answer text,
    created_at timestamptz not null default now(),
    reviewed_at timestamptz
);

create index if not exists custom_prompt_submissions_learner_email_idx
    on public.custom_prompt_submissions (learner_email);

create index if not exists custom_prompt_submissions_status_idx
    on public.custom_prompt_submissions (status);
